name: build-and-push-ghcr

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  IMAGE_NAME: comfyui-hf

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Free a ton of space (uses the latest tagged release v10)
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 1024
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          overprovision-lvm: true

      # Extra safety: manual cleanup even if the step above already ran
      - name: Manual free space (fallback)
        if: always()
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/share/boost || true
          sudo rm -rf /opt/hostedtoolcache || true
          sudo docker image prune -af || true
          sudo docker builder prune -af || true
          sudo apt-get clean || true
          df -h

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          provenance: false

      - name: Cleanup
        if: always()
        run: |
          docker system df || true
          docker image prune -af || true
          docker builder prune -af || true
